config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/login' => 'sessions#new'
  post '/login'=> 'sessions#create'

  get '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users
  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: {minimum: 5}, allow_nil: true
  has_many :projects, dependent: :destroy

  validates(:name, presence: true)
  validates(:email, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def create
    @project = Project.new(project_params)
    @user = User.find(session[:user_id])
    @project.user = @user

    if @project.save
      redirect_to @project, notice: 'Project was successfully created!'
    else
      render :new
    end
  end

  def new
    @project = Project.new
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated!'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted.'
  end

private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      # session[:user_id] = user.id.to_s
      redirect_to users_path
    else
     render :new
   end
  end

  # def update
  #   @user = User.find(params[:id])
  #   if @user.update_attributes(user_params)
  #     flash[:success] = "Profile updated"
  #     redirect_to @user
  #   else
  #     render 'edit'
  #   end
  # end
  #
  # def edit
  #   user = User.find_by(params[:id])
  # end

  def destroy
    @sessions.destroy(:user_id)
    redirect_to login_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  	before_action :set_task, only: [:show, :edit, :update, :destroy]

    def index
      @tasks = Task.all
    end

    def new
      @project = Project.find(params[:project_id])
      @task = Project.new
    end

  	def create
      @project = Project.find(params[:project_id])
  		@task = Task.new(task_params)

      if @task.save
        redirect_to @project, notice: "Your project was successfully created!"
      else
        redirect_to @project, notice: "Your project was not successfully created!"
      end
  	end

    def edit
    end

    def update
      if @task.update_attributes(task_params)
        redirect_to @task, notice: 'Task was successfully updated!'
      else
        render :edit
      end
    end

  	def destroy
  		@task.destroy
  		redirect_to @project, notice: 'Task was successfully deleted!'
  	end


  private
  	def set_task
      @task = Task.find(params[:project_task_id])
  		@project = Project.find(params[:project_id])
  	end

  	def task_params
      params.require(:task).permit(:task_date, :title, :description, :user_id, :project_id)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Productivity Planner!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @project = Project.new
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
      redirect_to users_path
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def redirect_to_default
      redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
 def gravatar_for(user)
   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
   image_tag(gravatar_url, alt: user.name, class: "gravatar")
 end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Ruby PP</title>
  </head>
  <body>

  <header>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul class="nav navbar-nav">
            <li><%= link_to "Productivity Planner", root_path %></li>
          </ul>
        </div>

        <div class="collapse navbar-collapse navbar-right" id="mynavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Projects", projects_path %></li>
            <li>
              <% if !current_user %>
                <!-- <%= link_to "Logout", :controller => 'sessions', :action => 'destroy' %> -->
                <%= link_to "Log In", login_path %>
              <% else %>
                <%= link_to "Log In", logout_path %>
              <% end %>
            </li>
          </ul>
        </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MPP</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-info">
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_resets_new, url: password_resets_new_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="container-fluid" >
  <div class="row">
    <div class="col-sm-12 text-center">

    <%= form_for(@project) do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

  <div class="field">
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
    <br>
    <br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<br>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1 class="project_title">Edit Project</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="container-fluid" >
  <div class="row">
    <div class="col-sm-12 text-center">
      <table class = "table table-hover">

        <tbody>
          <% @projects.each do |project| %>
            <tr>
            <td><%= link_to project.title, project_path(project.id) %></td>

          </tr>
          <% end %>
        </tbody>
      </table>

<br>

    <%= link_to "Create New Project", new_project_path, class: "btn btn-info" %>


</div>
</div>
</div>

app/views/projects/new.html.erb
<div class="Absolute-Center forms">
  <div class="container-fluid" >
    <div class="row">
      <div class="col-sm-12 text-center">
        <h1 class="project_title">New Project</h1>

        <%= render 'form' %>
        
    <%= link_to 'Back to Projects', projects_path, class: "btn btn-info" %>
  </div>
  </div>
</div>

app/views/projects/show.html.erb
<table class = "table">
 <thead>
    <tr>
       <th><%= @project.title %></th>
    </tr>
 </thead>
 <tbody>
   <% @project.tasks.each do |task| %>
   <tr>
     <td><%= task.title %></td>
   </tr>
   <% end %>
 </tbody>
</table>

<hr>


 <%= form_for([@project, @project.tasks.build]) do |f| %>
   <div class="field">
     <%= f.label :task %>
     <%= f.text_field :title %>
   </div>
   <div class="field">
     <%= f.label :time_to_do%>
     <%= f.text_field :time_to_do%>
   </div>
   <div class="field">
     <%= f.label :due_date %>
     <%= f.date_field :due_date %>
   </div>
   <div class="field">
     <%= f.label :completed_at%>
     <%= f.date_field :completed_at%>
   </div>

   <div>
     <%= f.hidden_field :project_id, :value => @project.id %>
   </div>

   <div class="actions">
     <%= f.submit %>
   </div>
 <% end %>

  <hr>

  <span class="bottomalign"><%= link_to 'Back to Projects', projects_path, class: "btn btn-info" %></span>
  <span class="bottomalign"><%= link_to 'Delete Project', project_path(@project), data: {confirm: 'Are u sure?'}, method: :delete, class: "btn btn-danger" %></span>
  <%= button_to 'Logout', logout_path, :method => :delete %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build]) do |f| %>
  <div class="field">
    <%= f.label :task %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :time_to_do%>
    <%= f.text_field :time_to_do%>
  </div>
  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_field :due_date %>
  </div>
  <div class="field">
    <%= f.label :completed_at%>
    <%= f.date_field :completed_at%>
  </div>

  <div>
    <%= f.hidden_field :project_id, :value => @project.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
  


<div class="links">
  <%= link_to "New Project", new_project_path %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container-fluid" >
  <div class="row">
    <div class="col-sm-12 text-center">
    <%= form_for(@user) do |f| %>
    <form id="signup" method="post" action="/signup">
      <h1>create an account</h1>


      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.text_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation %>
      </div>

      <hr>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    </form>
    <% end %>


</div>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="pagination-centered">
  <section class="user_info">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </section>

  <hr>
    <%= link_to "Create New Project", new_project_path, class: "btn btn-info" %>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron text-center">
  <div class="bg-info">
  <h1>Welcome to Your Productivity Planner</h1>

  <h4>
    Organize & Plan Your Projects<br>
    All In One Place AND...<br>
    Link To Your Google Calendar
  </h4>

  <img class="img-responsive" src="http://orderinthehouse.com/wp-content/uploads/2015/05/ToDoList.jpg" alt="To Do List" width="460" height="345">

  <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary round" %>
  </div>
</div>